import type { AuditLogEntry, SystemRole, UserAccount } from '../types'

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'usr_1',
    name: 'Karthikeyan Analysis Lead',
    email: 'karthikeyan@studycircle.org',
    role: 'Administrator',
    department: 'Executive Board',
    status: 'Active',
    lastActive: '2 mins ago',
    createdDate: '2026-01-10',
    permissions: ['doc:all', 'workflow:all', 'users:all', 'audit:all', 'system:all'],
  },
  {
    id: 'usr_2',
    name: 'Dr. Ananya Sharma',
    email: 'ananya.sharma@studycircle.org',
    role: 'Editor',
    department: 'Mathematics & Science',
    status: 'Active',
    lastActive: '15 mins ago',
    createdDate: '2026-02-14',
    permissions: ['doc:read', 'doc:edit', 'doc:compile', 'doc:export', 'workflow:run'],
  },
  {
    id: 'usr_3',
    name: 'Rajesh Varma',
    email: 'rajesh.v@studycircle.org',
    role: 'Document Specialist',
    department: 'Scanning & AI OCR',
    status: 'Active',
    lastActive: '1 hour ago',
    createdDate: '2026-03-01',
    permissions: ['doc:read', 'doc:edit', 'doc:scan', 'doc:align'],
  },
  {
    id: 'usr_4',
    name: 'Priya Sundaram',
    email: 'priya.s@studycircle.org',
    role: 'Viewer',
    department: 'Quality Assurance',
    status: 'Active',
    lastActive: '3 hours ago',
    createdDate: '2026-03-20',
    permissions: ['doc:read', 'doc:export'],
  },
  {
    id: 'usr_5',
    name: 'Vikram Malhotra',
    email: 'vikram.m@studycircle.org',
    role: 'Administrator',
    department: 'IT Infrastructure',
    status: 'Active',
    lastActive: 'Yesterday at 18:45',
    createdDate: '2026-01-15',
    permissions: ['doc:all', 'workflow:all', 'users:all', 'audit:all', 'system:all'],
  },
  {
    id: 'usr_6',
    name: 'Meera Krishnan',
    email: 'meera.k@studycircle.org',
    role: 'Editor',
    department: 'Economics & Humanities',
    status: 'Inactive',
    lastActive: '3 days ago',
    createdDate: '2026-04-05',
    permissions: ['doc:read', 'doc:edit', 'doc:compile'],
  },
  {
    id: 'usr_7',
    name: 'Suresh Nair',
    email: 'suresh.n@studycircle.org',
    role: 'Audit Manager',
    department: 'Compliance & Audit',
    status: 'Active',
    lastActive: '5 hours ago',
    createdDate: '2026-05-12',
    permissions: ['audit:all', 'doc:read', 'users:view'],
  },
]

export const INITIAL_ROLES: SystemRole[] = [
  {
    id: 'role_admin',
    name: 'Administrator',
    description: 'Full root access to system settings, user governance, role definitions, audit logs, and document suites.',
    userCount: 2,
    isSystem: true,
    permissions: [
      'doc:create', 'doc:read', 'doc:edit', 'doc:delete', 'doc:export', 'doc:scan', 'doc:align', 'doc:compile',
      'workflow:view', 'workflow:edit', 'workflow:execute',
      'users:view', 'users:create', 'users:edit', 'users:delete', 'users:roles',
      'audit:view', 'audit:export',
      'system:config', 'system:security',
    ],
  },
  {
    id: 'role_editor',
    name: 'Editor',
    description: 'Complete authoring capabilities, TeX formula rendering, question bank formatting, and document export.',
    userCount: 2,
    isSystem: true,
    permissions: [
      'doc:create', 'doc:read', 'doc:edit', 'doc:export', 'doc:scan', 'doc:align', 'doc:compile',
      'workflow:view', 'workflow:execute',
      'users:view',
    ],
  },
  {
    id: 'role_viewer',
    name: 'Viewer',
    description: 'Read-only document inspection, print previewing, and PDF downloading without modification rights.',
    userCount: 1,
    isSystem: true,
    permissions: [
      'doc:read', 'doc:export',
    ],
  },
  {
    id: 'role_doc_spec',
    name: 'Document Specialist',
    description: 'Specialized access for high-speed OCR document scanning, alignment correction, and image processing.',
    userCount: 1,
    isSystem: false,
    permissions: [
      'doc:create', 'doc:read', 'doc:edit', 'doc:scan', 'doc:align', 'doc:compile',
      'workflow:view', 'workflow:execute',
    ],
  },
  {
    id: 'role_auditor',
    name: 'Audit Manager',
    description: 'Compliance auditing, security logs verification, and event stream exports.',
    userCount: 1,
    isSystem: false,
    permissions: [
      'audit:view', 'audit:export',
      'users:view',
      'doc:read',
    ],
  },
]

export const ALL_PERMISSIONS_LIST = [
  {
    category: 'Document Operations',
    items: [
      { id: 'doc:create', name: 'Create Documents', desc: 'Allows creating new publication books and document files.' },
      { id: 'doc:read', name: 'Read & Preview Documents', desc: 'Allows viewing document text, math formulas, and layout previews.' },
      { id: 'doc:edit', name: 'Edit Content & Layout', desc: 'Allows modifying headings, paragraphs, MCQs, and header/footer settings.' },
      { id: 'doc:delete', name: 'Delete Documents', desc: 'Allows permanent deletion of documents from the publication database.' },
      { id: 'doc:export', name: 'Export Multi-Size PDF', desc: 'Allows compiling press-ready PDFs for A4, B5, and 8x8 formats.' },
      { id: 'doc:scan', name: 'Run AI OCR Scanning', desc: 'Allows scanning physical documents and image text conversion.' },
      { id: 'doc:align', name: 'Auto-Align & Format', desc: 'Allows triggering automatic layout alignment and pagination engines.' },
      { id: 'doc:compile', name: 'Compile Formula & TeX', desc: 'Allows executing live TeX math formula compilation.' },
    ],
  },
  {
    category: 'Workflow Automation',
    items: [
      { id: 'workflow:view', name: 'View Workflows', desc: 'Allows viewing automated processing pipelines and rules.' },
      { id: 'workflow:edit', name: 'Edit Workflow Rules', desc: 'Allows defining custom automation rules and trigger conditions.' },
      { id: 'workflow:execute', name: 'Execute Batch Jobs', desc: 'Allows running batch document processing and formatting queues.' },
    ],
  },
  {
    category: 'User Management',
    items: [
      { id: 'users:view', name: 'View User Directory', desc: 'Allows inspecting team member profiles, emails, and active roles.' },
      { id: 'users:create', name: 'Add New Users', desc: 'Allows inviting new team members and creating client accounts.' },
      { id: 'users:edit', name: 'Modify User Profiles', desc: 'Allows editing user details, deactivating accounts, and resetting passwords.' },
      { id: 'users:delete', name: 'Delete User Accounts', desc: 'Allows removing user accounts permanently.' },
      { id: 'users:roles', name: 'Manage Role Definitions', desc: 'Allows defining custom roles and configuring granular permission flags.' },
    ],
  },
  {
    category: 'System & Security',
    items: [
      { id: 'audit:view', name: 'View Security Audit Logs', desc: 'Allows tracking system activity streams and user actions.' },
      { id: 'audit:export', name: 'Export Audit Logs', desc: 'Allows downloading audit trail data in CSV or JSON format.' },
      { id: 'system:config', name: 'Configure System Settings', desc: 'Allows managing global paper standards, fonts, and defaults.' },
      { id: 'system:security', name: 'Security & Access Control', desc: 'Allows configuring authentication rules, IP restrictions, and session timeouts.' },
    ],
  },
]

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log_101',
    timestamp: '2026-08-08 13:05:12',
    user: 'Karthikeyan Analysis Lead',
    userEmail: 'karthikeyan@studycircle.org',
    role: 'Administrator',
    action: 'MODIFIED USER PERMISSIONS',
    category: 'User Management',
    details: 'Updated granted permissions for Dr. Ananya Sharma (Editor role)',
    ipAddress: '192.168.1.42',
    status: 'SUCCESS',
  },
  {
    id: 'log_102',
    timestamp: '2026-08-08 12:48:30',
    user: 'Rajesh Varma',
    userEmail: 'rajesh.v@studycircle.org',
    role: 'Document Specialist',
    action: 'RUN AUTOMATED OCR SCAN',
    category: 'Document Processing',
    details: 'Processed scanned document: Class 12 Maths Chapter 02 (4 pages batch)',
    ipAddress: '192.168.1.88',
    status: 'SUCCESS',
  },
  {
    id: 'log_103',
    timestamp: '2026-08-08 11:20:15',
    user: 'Vikram Malhotra',
    userEmail: 'vikram.m@studycircle.org',
    role: 'Administrator',
    action: 'NEW USER CREATED',
    category: 'User Management',
    details: 'Created user account for Suresh Nair assigned to Audit Manager role',
    ipAddress: '192.168.1.15',
    status: 'SUCCESS',
  },
  {
    id: 'log_104',
    timestamp: '2026-08-08 10:15:02',
    user: 'Dr. Ananya Sharma',
    userEmail: 'ananya.sharma@studycircle.org',
    role: 'Editor',
    action: 'COMPILED DOCUMENT',
    category: 'Document Processing',
    details: 'Ran auto-align & TeX formula compilation for Integral Calculus manual',
    ipAddress: '192.168.1.64',
    status: 'SUCCESS',
  },
  {
    id: 'log_105',
    timestamp: '2026-08-08 09:30:44',
    user: 'System Security Safeguard',
    userEmail: 'system@studycircle.org',
    role: 'System',
    action: 'FAILED LOGIN ATTEMPT',
    category: 'System Security',
    details: 'Failed authentication check for external IP 203.0.113.5 (Rate limit applied)',
    ipAddress: '203.0.113.5',
    status: 'WARNING',
  },
  {
    id: 'log_106',
    timestamp: '2026-08-08 08:12:10',
    user: 'Karthikeyan Analysis Lead',
    userEmail: 'karthikeyan@studycircle.org',
    role: 'Administrator',
    action: 'ROLE DEFINITION UPDATED',
    category: 'Role Modified',
    details: 'Updated permission set for role Document Specialist (Added doc:align)',
    ipAddress: '192.168.1.42',
    status: 'SUCCESS',
  },
  {
    id: 'log_107',
    timestamp: '2026-08-07 17:40:22',
    user: 'Dr. Ananya Sharma',
    userEmail: 'ananya.sharma@studycircle.org',
    role: 'Editor',
    action: 'EXPORTED PUBLICATION PDF',
    category: 'Document Processing',
    details: 'Generated press-ready PDF export for Micro Economics (A4 format)',
    ipAddress: '192.168.1.64',
    status: 'SUCCESS',
  },
  {
    id: 'log_108',
    timestamp: '2026-08-07 15:10:00',
    user: 'Vikram Malhotra',
    userEmail: 'vikram.m@studycircle.org',
    role: 'Administrator',
    action: 'AUTOMATION RULE CREATED',
    category: 'Workflow Execution',
    details: 'Added automated rule: Auto-format incoming scanned formulas into TeX blocks',
    ipAddress: '192.168.1.15',
    status: 'SUCCESS',
  },
]
