import { useMemo, useRef, useState } from "react";
import type { BookDocument, BookMode, NavHandler } from "../types";
import { PAPER_LABELS } from "../types";
import { estimateBookStats } from "../lib/bookAi";
import { runPreflight } from "../lib/preflight";
import Icon from "../components/Icon";

export default function Dashboard({ library, onNewBook, onOpenBook, onDeleteBook, onRestore }: { onNavigate: NavHandler; onExport: () => void; onCommand: () => void; onNewBook: (mode?: BookMode) => void; library: BookDocument[]; onOpenBook: (book: BookDocument) => void; onDeleteBook: (id: string) => void; onRestore?: (file: File) => void }) {
  const [filter, setFilter] = useState<"all" | "qa" | "questions-only">("all");
  const [query, setQuery] = useState("");
  const [sort, setSort] = useState<"updated" | "title">("updated");
  const restoreRef = useRef<HTMLInputElement>(null);
  const filtered = useMemo(() => library.filter((book) => (filter === "all" || (book.bookMode || "qa") === filter) && book.title.toLowerCase().includes(query.trim().toLowerCase())).sort((a, b) => sort === "title" ? a.title.localeCompare(b.title) : b.updatedAt.localeCompare(a.updatedAt)), [library, filter, query, sort]);
  const relative = (iso: string) => { const minutes = Math.max(0, Math.round((Date.now() - new Date(iso).getTime()) / 60000)); return minutes < 1 ? "Just now" : minutes < 60 ? `${minutes}m ago` : minutes < 1440 ? `${Math.round(minutes / 60)}h ago` : new Date(iso).toLocaleDateString(); };
  return <div className="h-full overflow-y-auto bg-slate-50">
    <header className="sticky top-0 z-10 h-16 px-8 flex items-center border-b border-slate-200 bg-white"><div><h1 className="text-base font-semibold text-slate-950">Library</h1><p className="text-xs text-slate-500">Local academic publications</p></div><div className="ml-auto flex items-center gap-2"><button className="secondary-button" onClick={() => restoreRef.current?.click()}><Icon name="import" className="w-3.5 h-3.5" />Restore project</button><button className="primary-button" onClick={() => onNewBook("qa")}><Icon name="plus" className="w-3.5 h-3.5" />Create publication</button><input ref={restoreRef} type="file" accept=".json,.publication.json" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file) onRestore?.(file); event.target.value = ""; }} /></div></header>
    <main className="max-w-[1400px] mx-auto px-8 py-7">
      <section className="grid grid-cols-2 gap-3 mb-7">
        <button onClick={() => onNewBook("qa")} className="creation-path"><div className="creation-icon"><Icon name="question" className="w-5 h-5" /></div><div className="text-left"><span className="text-sm font-semibold text-slate-950">Question Bank</span><p className="mt-0.5 text-xs text-slate-500">MCQs, A–E options, math, verified answers and six-column answer keys</p></div><Icon name="chevron" className="w-4 h-4 ml-auto text-slate-400" /></button>
        <button onClick={() => onNewBook("questions-only")} className="creation-path"><div className="creation-icon"><Icon name="book" className="w-5 h-5" /></div><div className="text-left"><span className="text-sm font-semibold text-slate-950">Study Book / Syllabus</span><p className="mt-0.5 text-xs text-slate-500">Chapters, sections, theorem blocks, examples, exercises and tables</p></div><Icon name="chevron" className="w-4 h-4 ml-auto text-slate-400" /></button>
      </section>
      <section className="bg-white border border-slate-200 rounded-lg overflow-hidden">
        <div className="h-14 px-4 flex items-center border-b border-slate-200"><h2 className="text-sm font-semibold text-slate-900">Recent publications <span className="font-normal text-slate-400">{library.length}</span></h2><div className="ml-auto flex items-center gap-2"><div className="relative"><Icon name="search" className="absolute left-2.5 top-2.5 w-3.5 h-3.5 text-slate-400" /><input aria-label="Search publications" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search" className="h-9 w-52 pl-8 pr-3 text-xs border border-slate-300 rounded-md outline-none focus:ring-2 focus:ring-indigo-100 focus:border-indigo-500" /></div><select aria-label="Filter publication mode" className="control-select" value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)}><option value="all">All modes</option><option value="qa">Question Bank</option><option value="questions-only">Study Book</option></select><select aria-label="Sort publications" className="control-select" value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="updated">Last edited</option><option value="title">Title</option></select></div></div>
        {filtered.length === 0 ? <div className="py-16 px-6 text-center"><div className="w-12 h-12 mx-auto rounded-full bg-slate-100 text-slate-400 flex items-center justify-center"><Icon name="library" className="w-6 h-6" /></div><h3 className="mt-4 text-sm font-semibold text-slate-900">{library.length ? "No matching publications" : "Create your first publication"}</h3><p className="mt-1 text-xs text-slate-500">{library.length ? "Adjust the search or filters." : "Choose Question Bank or Study Book. Your work autosaves locally."}</p>{!library.length && <button onClick={() => onNewBook("qa")} className="primary-button mt-5"><Icon name="plus" className="w-3.5 h-3.5" />Create publication</button>}</div> : <div className="divide-y divide-slate-100">{filtered.map((book) => { const stats = estimateBookStats(book); const issues = runPreflight(book); const blocking = issues.filter((item) => item.severity === "error").length; return <article key={book.id} className="group min-h-24 px-4 py-3 grid grid-cols-[64px_minmax(240px,1fr)_130px_140px_110px_72px] gap-4 items-center hover:bg-slate-50 cursor-pointer" onClick={() => onOpenBook(book)} onKeyDown={(event) => event.key === "Enter" && onOpenBook(book)} tabIndex={0}>
          <div className="w-12 h-16 bg-[#fffef9] border border-slate-300 shadow-sm p-1.5"><div className="h-1 bg-slate-800 mb-1" />{Array.from({ length: 7 }).map((_, index) => <div key={index} className="h-[2px] bg-slate-300 mb-1" />)}</div><div className="min-w-0"><h3 className="text-[13px] font-semibold text-slate-950 truncate">{book.title}</h3><p className="mt-1 text-[11px] text-slate-500 truncate">{book.subtitle || book.headerFooter.chapterTitle || "Untitled chapter"}</p><span className="mt-2 inline-flex text-[9px] font-semibold uppercase tracking-wide text-indigo-700">{book.bookMode === "questions-only" ? "Study Book" : "Question Bank"}</span></div><div><span className="block text-xs font-medium text-slate-700">{stats.pages} page{stats.pages === 1 ? "" : "s"}</span><span className="text-[10px] text-slate-400">{book.headerFooter.layoutColumns} column{book.headerFooter.layoutColumns === 1 ? "" : "s"}</span></div><div><span className="block text-[11px] text-slate-700 truncate" title={PAPER_LABELS[book.paperSize]}>{PAPER_LABELS[book.paperSize]}</span><span className="text-[10px] text-slate-400">Print size</span></div><div>{blocking ? <span className="status-badge status-error">{blocking} blocking</span> : issues.length ? <span className="status-badge status-warning">Review</span> : <span className="status-badge status-good">Ready</span>}<span className="block mt-1 text-[10px] text-slate-400">{relative(book.updatedAt)}</span></div><button aria-label={`Delete ${book.title}`} className="icon-button opacity-0 group-hover:opacity-100 focus:opacity-100 text-slate-400 hover:text-rose-600" onClick={(event) => { event.stopPropagation(); if (window.confirm(`Delete “${book.title}”? This cannot be undone.`)) onDeleteBook(book.id); }}><Icon name="trash" className="w-4 h-4" /></button>
        </article>; })}</div>}
      </section>
    </main>
  </div>;
}
