import { useState } from "react";
import type { BookMode, Page } from "../types";
import Icon, { type IconName } from "./Icon";

export default function Sidebar({ activePage, onNavigate, onCommandPalette, onNewBook }: { activePage: Page; onNavigate: (page: Page) => void; onExport?: () => void; onCommandPalette?: () => void; onNewBook: (mode?: BookMode) => void }) {
  const [collapsed, setCollapsed] = useState(false);
  const destinations: Array<{ id: Page; label: string; icon: IconName }> = [
    { id: "dashboard", label: "Library", icon: "library" }, { id: "templates", label: "Templates", icon: "template" }, { id: "import-queue", label: "OCR → Print", icon: "import" }, { id: "settings", label: "Settings", icon: "settings" },
  ];
  return <aside className={`h-full shrink-0 bg-slate-950 text-slate-300 border-r border-slate-800 flex flex-col transition-[width] duration-150 ${collapsed ? "w-16" : "w-56"}`}>
    <div className="h-16 px-3 flex items-center border-b border-slate-800"><div className="w-8 h-8 rounded-md bg-indigo-600 text-white flex items-center justify-center shrink-0"><Icon name="book" className="w-4 h-4" /></div>{!collapsed && <div className="ml-2.5 min-w-0"><p className="text-xs font-semibold text-white truncate">Folio Academic</p><button className="text-[10px] text-slate-400 hover:text-white flex items-center gap-1">Publishing workspace <Icon name="chevron" className="w-2.5 h-2.5 rotate-90" /></button></div>}<button onClick={() => setCollapsed((value) => !value)} aria-label={collapsed ? "Expand navigation" : "Collapse navigation"} className="ml-auto w-7 h-7 flex items-center justify-center rounded text-slate-400 hover:bg-slate-800 hover:text-white"><Icon name="chevron" className={`w-3.5 h-3.5 ${collapsed ? "" : "rotate-180"}`} /></button></div>
    <div className="p-2.5"><button onClick={() => onNewBook("qa")} className={`w-full h-9 rounded-md bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-xs flex items-center justify-center gap-2 ${collapsed ? "px-0" : "px-3"}`}><Icon name="plus" className="w-4 h-4" />{!collapsed && "Create publication"}</button></div>
    <nav className="px-2 flex-1" aria-label="Workspace navigation">{destinations.map((item) => { const active = activePage === item.id || (item.id === "dashboard" && activePage === "documents"); return <button key={item.id} onClick={() => onNavigate(item.id)} title={collapsed ? item.label : undefined} className={`w-full h-9 my-0.5 rounded-md flex items-center gap-2.5 text-xs font-medium ${collapsed ? "justify-center px-0" : "px-3"} ${active ? "bg-slate-800 text-white" : "text-slate-400 hover:bg-slate-900 hover:text-slate-100"}`}><Icon name={item.icon} className="w-4 h-4 shrink-0" />{!collapsed && item.label}</button>; })}</nav>
    <div className="p-2 border-t border-slate-800"><button onClick={onCommandPalette} className={`w-full h-9 rounded-md flex items-center gap-2 text-xs whitespace-nowrap text-slate-400 hover:bg-slate-900 hover:text-white ${collapsed ? "justify-center" : "px-2"}`}><Icon name="command" className="w-4 h-4 shrink-0" />{!collapsed && <><span>Command palette</span><kbd className="ml-auto text-[9px] border border-slate-700 rounded px-1">Ctrl K</kbd></>}</button><div className={`mt-2 p-2 rounded-md bg-slate-900 flex items-center ${collapsed ? "justify-center" : "gap-2"}`}><div className="w-7 h-7 rounded-full bg-slate-700 text-[10px] font-semibold flex items-center justify-center text-white">KP</div>{!collapsed && <div className="min-w-0"><p className="text-[11px] font-medium text-slate-200 truncate">Karthikeyan Publishing</p><p className="text-[9px] text-slate-500">Local workspace</p></div>}</div></div>
  </aside>;
}
