import type { PublicationTemplate } from "../lib/templates";
import { PUBLICATION_TEMPLATES } from "../lib/templates";
import Icon from "./Icon";

export default function TemplatesPanel({ onSelectTemplate }: { onSelectTemplate?: (template: PublicationTemplate) => void }) {
  return <div className="h-full overflow-y-auto bg-slate-50">
    <header className="sticky top-0 z-10 h-16 px-8 flex items-center border-b border-slate-200 bg-white"><div><h1 className="text-base font-semibold text-slate-950">Publication templates</h1><p className="text-xs text-slate-500">Real editable settings—not flattened artwork</p></div></header>
    <main className="max-w-[1200px] p-8"><div className="grid grid-cols-1 xl:grid-cols-2 gap-4">{PUBLICATION_TEMPLATES.map((template, index) => <article key={template.id} className="bg-white border border-slate-200 rounded-lg overflow-hidden flex min-h-56">
      <div className="w-40 shrink-0 bg-slate-200 p-5 flex items-center justify-center"><div className={`relative bg-[#fffef9] shadow-md border border-slate-300 ${template.paperSize === "A4" ? "w-[90px] h-[128px]" : "w-[96px] h-[128px]"}`}><div className="absolute left-3 right-3 top-3 h-1 bg-slate-800" /><div className="absolute left-3 right-3 top-7 bottom-5 flex gap-1">{Array.from({ length: template.columns }).map((_, column) => <div key={column} className="flex-1 space-y-1">{Array.from({ length: 10 }).map((__, line) => <div key={line} className="h-[2px] bg-slate-300" />)}</div>)}</div><div className="absolute left-3 right-3 bottom-3 h-[2px] bg-slate-700" /></div></div>
      <div className="p-5 flex-1"><div className="flex items-start justify-between gap-3"><div><span className="text-[10px] font-semibold uppercase tracking-wider text-indigo-700">{index < 2 ? "Reference matched" : "Academic"}</span><h2 className="mt-1 text-sm font-semibold text-slate-950">{template.title}</h2></div>{index === 0 && <span className="status-badge status-good">Recommended</span>}</div><p className="mt-2 text-xs leading-5 text-slate-600">{template.description}</p><ul className="mt-3 grid grid-cols-2 gap-x-3 gap-y-1">{template.features.map((feature) => <li key={feature} className="text-[11px] text-slate-600 flex items-center gap-1.5"><Icon name="check" className="w-3 h-3 text-emerald-600" />{feature}</li>)}</ul><div className="mt-4 flex items-center justify-between"><span className="text-[10px] text-slate-500">{template.paperSize === "REFERENCE_180_240" ? "180 × 240 mm" : template.paperSize} · {template.columns} column{template.columns > 1 ? "s" : ""}</span><button className="primary-button" onClick={() => onSelectTemplate?.(template)} disabled={!onSelectTemplate}>Use template</button></div></div>
    </article>)}</div></main>
  </div>;
}
